# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 16:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basestudent', '0006_auto_20160926_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='basestudent.Group', verbose_name='Группа, к которой прикреплен студент'),
        ),
    ]
